# docker-compose.yml

version: '3.7'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate-next-sass
    image: boilerplate-next-sass
    restart: always
    command: npm run dev
    volumes:
      - ./:/boilerplate-next-sass
    ports:
      - 3000:3000
