name: Executar testes Jest

on:
  push:
    branches: master
  pull_request:
    branches: ${GITHUB_HEAD_REF}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Instalar dependências
      run: npm ci

    - name: Executar testes
      run: npm test
